dataset:
  directory: ../dataset/
  vocabulary_treshold: 10
  image_resize: 224

training:
  gpu_id: 0 # specify the GPU id for learning process
  batch_size: 64 # the number of data contained in every batch
  epoch: 10
  model_export_dir: /home/rizal # path directory for save the model
  learning_rate: 0.001
  weight_decay: 0.000001

model:
  encoder:
    linear_visual_features:
      out_size: 1024
    lstm:
      hidden_size: 1024
      num_layers: 2 
  decoder:


logging:
  tensorboard: 